; ENTITY HOME

[app/home]
controller = "Home"
method     = "display"
security = "ALL"
js = "pages/home/home.js"
css = ""

[carte/jo2024]
controller = "Home"
method     = "displayJo2024"
security = "ALL"
js = ""
css = ""


; ENTITY AUTH

[auth/display]
controller = "Auth"
method     = "displayAuth"
security = "ALL"
js = "pages/auth/auth.js vendor/sweet-alert.js"
css = "sweet-alert.css"

[auth/check]
controller = "Auth"
method     = "checkAuth"
security = "ALL"
js = ""
css = ""

[auth/create-password]
controller = "Auth"
method     = "createPassword"
security = "ALL"
js = "pages/auth/lost-password.js"
css = ""

[auth/lost-password]
controller = "Auth"
method     = "lostPassword"
security = "ALL"
js = "pages/auth/lost-password.js"
css = ""

[auth/lost-password-confirm]
controller = "Auth"
method     = "lostPasswordConfirm"
security = "ALL"
js = "pages/auth/lost-password-confirm.js"
css = ""

; MON COMPTE
[utilisateur/mon-compte]
controller = "User"
method     = "showMyAccount"
security = "ALL"
js = "pages/user/my-account.js"
css = ""


[utilisateur/ajouter-un-enfant]
controller = "User"
method     = "showAddChild"
security = "ALL"
js = "vendor/jquery-ui.js google-maps vendor/sweet-alert.js pages/user/add-child.js"
css = "sweet-alert.css jquery-ui.css jquery-ui-theme.css"

[utilisateur/livrets]
controller = "User"
method     = "showBooklets"
security = "ALL"
js = "vendor/jquery-ui.js pages/user/booklets.js"
css = "sweet-alert.css jquery-ui.css jquery-ui-theme.css"

[utilisateur/mes-photos]
controller = "User"
method     = "showPhotos"
security = "ALL"
js = "vendor/jquery-ui.js pages/user/photos.js"
css = "sweet-alert.css jquery-ui.css jquery-ui-theme.css"

[utilisateur/ajouter-un-profil]
controller = "User"
method     = "showAddPerson"
security = "ALL"
js = "pages/user/add-person.js vendor/sweet-alert.js"
css = "sweet-alert.css"

[utilisateur/historique]
controller = "User"
method     = "showHistoric"
security = "ALL"
js = "pages/user/historic.js"
css = ""

[utilisateur/paiement-en-attente]
controller = "User"
method     = "awaitingPaiement"
security = "ALL"
js = ""
css = ""

[utilisateur/mes-enfants]
controller = "User"
method     = "showListChild"
security = "ALL"
js = ""
css = ""

[utilisateur/profils-associes]
controller = "User"
method     = "showListPerson"
security = "ALL"
js = "pages/user/list-person.js"
css = ""


[utilisateur/unassociate]
controller = "User"
method     = "personUnassociate"
security = "ALL"
js = ""
css = ""


[utilisateur/associer-les-enfants]
controller = "User"
method     = "childAssociated"
security = "ALL"
js = "pages/user/childAssociated.js"
css = ""

[utilisateur/doAssociation]
controller = "User"
method     = "doAssociation"
security = "ALL"
js = ""
css = ""



[utilisateur/profil]
controller = "User"
method     = "showProfilPerson"
security = "ALL"
js = "pages/user/profil-person.js vendor/sweet-alert.js"
css = "sweet-alert.css"


[utilisateur/ajouter-un-justificatif]
controller = "User"
method     = "addJustificatif"
security = "ALL"
js = ""
css = ""

[enfant/profil]
controller = "User"
method     = "showChildProfil"
security = "ALL"
js = "pages/user/profil-child.js vendor/sweet-alert.js"
css = "sweet-alert.css"


; ENTITY PAYMENT

[payment/success]
controller = "Payment"
method     = "Success"
security = "ALL"
js = ""
css = ""


[payment/confirmation]
controller = "Payment"
method     = "Confirmation"
security = "ALL"
js = ""
css = ""


; ENTITY BLOG

[blog/list]
controller = "Blog"
method     = "List"
security = "ALL"
js = "pages/blog/list.js"
css = ""


[blog/article]
controller = "Blog"
method     = "Article"
security = "ALL"
js = ""
css = ""



; PRODUITS

[ea/selection]
controller = "Product"
method     = "viewProduct"
security = "ALL"
js = "vendor/sweet-alert.js vendor/jquery-ui.js pages/product/display.js"
css = "sweet-alert.css jquery-ui.css jquery-ui-theme.css"

[ea/a-la-carte]
controller = "Product"
method     = "viewALaCarte"
security = "ALL"
js = "vendor/sweet-alert.js vendor/jquery-ui.js pages/product/alacarte.js"
css = "sweet-alert.css jquery-ui.css jquery-ui-theme.css"

[ea/loadProductALacarte]
controller = "Product"
method     = "viewProductALaCarte"
security = "ALL"
js = ""
css = ""

[ea/cart]
controller = "Product"
method     = "viewCart"
security = "ALL"
js = ""
css = ""

[ea/cartFromApp]
controller = "Product"
method     = "viewCart"
security = "ALL"
js = ""
css = ""

[ea/connectApp]
controller = "Auth"
method     = "connectApp"
security = "ALL"
js = ""
css = ""

[ea/category]
controller = "Product"
method     = "viewCategory"
security = "ALL"
js = "pages/category/category.js"
css = ""

[ea/directAddProduct]
controller = "Product"
method     = "directAddProduct"
security = "ALL"
js = ""
css = ""


[create/registration]
controller = "Product"
method     = "createRegistration"
security = "ALL"
js = ""
css = ""


[ea/countCart]
controller = "Product"
method     = "countCart"
security = "ALL"
js = ""
css = ""


; OTHER ROUTES

[savePhoto]
controller = "Photo"
method     = "savePhoto"
security = "ALL"
js = ""
css = ""

[sendRequest]
controller = "Api"
method     = "sendRequest"
security = "ALL"
js = ""
css = ""

[sendSMSNewPassword]
controller = "Api"
method     = "sendSMSNewPassword"
security = "ALL"
js = ""
css = ""

[sendMailLostPassword]
controller = "Mail"
method     = "LostPassword"
security = "ALL"
js = ""
css = ""